Drop director from manifest generation.

diff --git a/generate_deployment_manifest b/generate_deployment_manifest
--- a/generate_deployment_manifest
+++ b/generate_deployment_manifest
@@ -1,24 +1,26 @@
 #!/bin/bash
 
-templates=$(dirname $0)/templates
-uuid_stub_path=$(dirname $0)/uuid-stub.yml
+set -e
 
-infrastructure=$1
-director_uuid=$2
+which spiff > /dev/null 2>&1 || {
+  echo "Aborted. Please install spiff by following https://github.com/cloudfoundry-incubator/spiff#installation" 1>&2
+  exit 1
+}
 
-if [ "$#" -lt 2 ]; then
-  echo "usage: ./generate_deployment_manifest <warden|aws> <director_uuid> [stubs...]"
+templates="$(dirname $0)/templates"
+
+infrastructure="${1:?}"
+
+shift
+
+if [ "$infrastructure" != "aws" ] && \
+    [ "$infrastructure" != "warden" ] ; then
+  echo "Usage: ./scripts/generate_deployment_manifest <aws|warden> [stubs...]" 1>&2
   exit 1
 fi
 
-shift
-shift
-
-echo "director_uuid: ${director_uuid}" > $uuid_stub_path
-
 spiff merge \
-  $templates/k8s-deployment.yml \
-  $uuid_stub_path \
-  $templates/k8s-jobs.yml \
-  $templates/k8s-infrastructure-${infrastructure}.yml \
-  $*
+  "$templates/k8s-deployment.yml" \
+  "$templates/k8s-jobs.yml" \
+  "$templates/k8s-infrastructure-${infrastructure}.yml" \
+  "$@"
