Allow kubedns check to time out.
Prevents kubedns task from hanging forever if it fails.

diff --git a/jobs/create-kubernetes-dns/templates/run.erb b/jobs/create-kubernetes-dns/templates/run.erb
--- a/jobs/create-kubernetes-dns/templates/run.erb
+++ b/jobs/create-kubernetes-dns/templates/run.erb
@@ -5,7 +5,15 @@ PATH=$PATH:/var/vcap/packages/kubernetes/bin
 cd /var/vcap/jobs/create-kubernetes-dns/bin
 kubectl -s http://${API_HOST}:8080 apply -f skydns-controller.yaml
 kubectl -s http://${API_HOST}:8080 apply -f skydns-service.yaml
-until kubectl -s http://${API_HOST}:8080 get pod --namespace=kube-system | grep 'kube-dns-.* 4/4 '
-do
+
+counter=60
+until [ $counter -le 0 ]; do
+  if kubectl -s http://${API_HOST}:8080 get pod --namespace=kube-system | grep 'kube-dns-.* 3/3 '; then
+    exit 0
+  fi
   sleep 5
+  let counter-=1
 done
+
+echo "Failed to start KubeDNS"
+exit 1
