Check if server is down

diff --git a/jobs/kubernetes-minion/templates/drain.erb b/jobs/kubernetes-minion/templates/drain.erb
--- a/jobs/kubernetes-minion/templates/drain.erb
+++ b/jobs/kubernetes-minion/templates/drain.erb
@@ -32,13 +32,18 @@ fi
 POD_RETRIES=0
 MAX_POD_RETRIES=240
 
+set +e
 while true; do
-  if [ $(kubectl -s http://${API_HOST}:8080 get pods | tail -n +2 | grep -v Running | wc -l) -eq 0 ]; then
+  POD_OUTPUT=$(kubectl -s http://${API_HOST}:8080 get pods)
+
+  if [ $? -ne 0 ]; then
+    logger -t error "[BOSH Kubernetes Drain] Could not reach API host ${API_HOST}"
+  elif [ $(echo ${POD_OUTPUT} | tail -n +2 | grep -v Running | wc -l) -eq 0 ]; then
     break
   fi
 
   if [ ${POD_RETRIES} -gt ${MAX_POD_RETRIES} ]; then
-    logger -t error "[BOSH Post-Start] Kubernetes pods not in a running state, and did not come back while waiting"
+    logger -t error "[BOSH Kubernetes Drain] Kubernetes pods not in a running state, and did not come back while waiting"
     exit 1
   else
     POD_RETRIES=$((POD_RETRIES + 1))
