Move pod health to stop script

diff --git a/jobs/kubernetes-minion/templates/kubelet_ctl.erb b/jobs/kubernetes-minion/templates/kubelet_ctl.erb
--- a/jobs/kubernetes-minion/templates/kubelet_ctl.erb
+++ b/jobs/kubernetes-minion/templates/kubelet_ctl.erb
@@ -61,6 +61,28 @@ case $1 in
     ;;
 
   stop)
+    # Choose first non-self address; using self fails if etcd drain script runs first
+    <% addr = spec.networks.to_h.values.first.ip %>
+    API_HOST=<%= p('apiserver.hosts').select {|ip| ip != addr}.first %>
+    POD_RETRIES=0
+    MAX_POD_RETRIES=240
+
+    while true; do
+      if [ $(kubectl -s http://${API_HOST}:8080 get pods | tail -n +2 | grep -v Running | wc -l) -eq 0 ]; then
+        break
+      fi
+
+      if [ ${POD_RETRIES} -gt ${MAX_POD_RETRIES} ]; then
+        logger -t error "[BOSH Post-Start] Kubernetes pods not in a running state, and did not come back while waiting"
+        exit 1
+      else
+        POD_RETRIES=$((POD_RETRIES + 1))
+      fi
+
+      sleep 1
+    done
+
+
     kill_and_wait $PIDFILE
 
     ;;
